{ Struo.Lockfile -- Struo.lock, read and written.

  The lockfile is what makes a clone of a repository compile the same code the
  author compiled. The manifest says `fjson = "1.2.0"`, which is a range; the
  lockfile says which version in that range was actually chosen, and for a git
  dependency which commit, so `branch = "main"` stops being a moving target.

  It is generated, so unlike the manifest it is written through the TOML
  writer rather than edited surgically. The header says not to edit it by
  hand, and the entries are sorted by name so that two machines resolving the
  same graph produce byte-identical files and a diff shows only real changes.

  Commit it for a binary; leave it out of a library's repository, since what
  a library resolves to on its own says nothing about what it will resolve to
  inside somebody else's build. }
unit Struo.Lockfile;

{$mode objfpc}{$H+}

interface

uses
  SysUtils, Struo.Util.Strings, Struo.Types, Struo.SemVer;

const
  { Bumped when the format changes in a way an older Struo cannot read. A
    lockfile from the future is regenerated rather than misread. }
  CLockfileFormat = 1;

type
  TLockedPackage = record
    Name: string;
    Version: TSemVer;
    { As Struo.Source.DescribeSource renders it. }
    Source: string;
    { The names this package depends on, sorted. Recorded so `struo tree` can
      be drawn from the lockfile alone, without re-reading every manifest. }
    Dependencies: TStrArray;
  end;

  TLockedPackageArray = array of TLockedPackage;

  TLockfile = class
  public
    FormatVersion: Integer;
    Packages: TLockedPackageArray;

    constructor Create;

    { Reads APath. Returns an empty lockfile when the file is absent, since
      that is the normal state of a package nobody has built yet. Raises
      EStruoError when the file is there but unreadable. }
    class function Load(const APath: string): TLockfile;

    procedure Save(const APath: string);

    { The text that would be written. Used by --dry-run and by the staleness
      check, which compares text rather than re-parsing. }
    function Text: string;

    procedure Add(const APackage: TLockedPackage);
    function Find(const AName: string; out APackage: TLockedPackage): Boolean;
    function Count: Integer;

    { Sorts by name, so the file is reproducible. Called by Save. }
    procedure Sort;

    { True when every entry matches AOther, ignoring order. This is how
      `struo build` decides whether the lockfile it just resolved differs from
      the one on disk and therefore needs writing. }
    function SameAs(AOther: TLockfile): Boolean;
  end;

{ Builds an entry. Separated so the resolver does not have to know the record
  layout. }
function MakeLockedPackage(const AName: string; const AVersion: TSemVer;
  const ASource: string; const ADependencies: TStrArray): TLockedPackage;

implementation

uses
  Struo.Util.Fs, Struo.Toml.Value, Struo.Toml.Parser, Struo.Toml.Writer;

const
  CHeader =
    '# This file is generated by Struo.' + LineEnding +
    '# Do not edit it by hand; run `struo update` instead.' + LineEnding;

function MakeLockedPackage(const AName: string; const AVersion: TSemVer;
  const ASource: string; const ADependencies: TStrArray): TLockedPackage;
var
  I, J: Integer;
  LSwap: string;
begin
  Result.Name := AName;
  Result.Version := AVersion;
  Result.Source := ASource;
  Result.Dependencies := Copy(ADependencies, 0, Length(ADependencies));

  { Sorted, because the order a resolver happened to visit them in is not
    information and would show up as diff noise. }
  for I := 1 to High(Result.Dependencies) do
  begin
    LSwap := Result.Dependencies[I];
    J := I - 1;
    while (J >= 0) and (CompareStr(Result.Dependencies[J], LSwap) > 0) do
    begin
      Result.Dependencies[J + 1] := Result.Dependencies[J];
      Dec(J);
    end;
    Result.Dependencies[J + 1] := LSwap;
  end;
end;

constructor TLockfile.Create;
begin
  inherited Create;
  FormatVersion := CLockfileFormat;
end;

function TLockfile.Count: Integer;
begin
  Result := Length(Packages);
end;

procedure TLockfile.Add(const APackage: TLockedPackage);
begin
  SetLength(Packages, Length(Packages) + 1);
  Packages[High(Packages)] := APackage;
end;

function TLockfile.Find(const AName: string; out APackage: TLockedPackage): Boolean;
var
  I: Integer;
begin
  for I := 0 to High(Packages) do
    if SameText(Packages[I].Name, AName) then
    begin
      APackage := Packages[I];
      Exit(True);
    end;
  APackage := Default(TLockedPackage);
  Result := False;
end;

procedure TLockfile.Sort;
var
  I, J: Integer;
  LSwap: TLockedPackage;
begin
  for I := 1 to High(Packages) do
  begin
    LSwap := Packages[I];
    J := I - 1;
    while (J >= 0) and (CompareStr(Packages[J].Name, LSwap.Name) > 0) do
    begin
      Packages[J + 1] := Packages[J];
      Dec(J);
    end;
    Packages[J + 1] := LSwap;
  end;
end;

class function TLockfile.Load(const APath: string): TLockfile;
var
  LDocument, LList, LEntry: TTomlValue;
  LPackage: TLockedPackage;
  I: Integer;
begin
  Result := TLockfile.Create;
  { No lockfile is the normal state of a package nobody has built. }
  if not PathIsFile(APath) then
    Exit;

  try
    try
      LDocument := ParseTomlFile(APath);
    except
      on E: ETomlError do
        raise EStruoError.CreateHint(
          Format('%s:%d:%d: %s',
            [ExtractFileName(APath), E.Line, E.Column, E.Message]),
          'delete it and run `struo build` to regenerate it');
    end;

    try
      Result.FormatVersion := LDocument.IntegerOr('version', CLockfileFormat);

      LList := LDocument.Find('package');
      if (LList <> nil) and LList.IsArray then
        for I := 0 to LList.Count - 1 do
        begin
          LEntry := LList.ItemAt(I);
          if not LEntry.IsTable then
            Continue;

          LPackage := Default(TLockedPackage);
          LPackage.Name := LEntry.StringOr('name', '');
          if LPackage.Name = '' then
            Continue;
          if not TryParseSemVer(LEntry.StringOr('version', ''), LPackage.Version) then
            Continue;
          LPackage.Source := LEntry.StringOr('source', '');
          LPackage.Dependencies := LEntry.StringsOr('dependencies', nil);
          Result.Add(LPackage);
        end;
    finally
      LDocument.Free;
    end;
  except
    Result.Free;
    raise;
  end;
end;

function TLockfile.Text: string;
var
  LRoot, LList, LEntry: TTomlValue;
  I: Integer;
begin
  Sort;

  LRoot := TTomlValue.NewTable;
  try
    LRoot.Put('version', TTomlValue.NewInteger(FormatVersion));

    LList := TTomlValue.NewArray;
    LList.IsArrayOfTables := True;
    LRoot.Put('package', LList);

    for I := 0 to High(Packages) do
    begin
      LEntry := TTomlValue.NewTable;
      LEntry.Put('name', TTomlValue.NewString(Packages[I].Name));
      LEntry.Put('version', TTomlValue.NewString(SemVerToStr(Packages[I].Version)));
      if Packages[I].Source <> '' then
        LEntry.Put('source', TTomlValue.NewString(Packages[I].Source));
      if Length(Packages[I].Dependencies) > 0 then
        LEntry.Put('dependencies',
          TTomlValue.NewStringArray(Packages[I].Dependencies));
      LList.Append(LEntry);
    end;

    Result := CHeader + WriteToml(LRoot);
  finally
    LRoot.Free;
  end;
end;

procedure TLockfile.Save(const APath: string);
begin
  WriteTextFile(APath, Text);
end;

function TLockfile.SameAs(AOther: TLockfile): Boolean;
var
  LMine, LTheirs: TLockedPackage;
  I: Integer;
begin
  if (AOther = nil) or (AOther.Count <> Count) then
    Exit(False);
  if AOther.FormatVersion <> FormatVersion then
    Exit(False);

  for I := 0 to High(Packages) do
  begin
    LMine := Packages[I];
    if not AOther.Find(LMine.Name, LTheirs) then
      Exit(False);
    { Source included: a dependency that moved from a path to git resolves to
      the same version and is still a change worth recording. }
    if (not SameSemVer(LMine.Version, LTheirs.Version)) or
       (LMine.Source <> LTheirs.Source) or
       (JoinStr(LMine.Dependencies, ',') <> JoinStr(LTheirs.Dependencies, ',')) then
      Exit(False);
  end;

  Result := True;
end;

end.
